# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imap < Formula
  desc "IMAP tools: backup, copy, move your emails between servers and locally"
  homepage "https://github.com/creativeprojects/imap"
  version "0.3.5"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/creativeprojects/imap/releases/download/v0.3.5/imap_0.3.5_darwin_amd64.tar.gz"
      sha256 "c0dfdc1614da68d22a38cc4642b5ffa008fe784b6e96ffe4fe91311c39a321d8"

      def install
        bin.install "imap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/creativeprojects/imap/releases/download/v0.3.5/imap_0.3.5_darwin_arm64.tar.gz"
      sha256 "40d152f1a08ea662f13a63c275f6cc0bc356a5ca523f27f95ba126c0e9c081aa"

      def install
        bin.install "imap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/creativeprojects/imap/releases/download/v0.3.5/imap_0.3.5_linux_amd64.tar.gz"
      sha256 "ae3ce99ffe2e614ac073a4ae8e5f012da80b7635fef4f1ffb823d5feea6b4c71"

      def install
        bin.install "imap"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/creativeprojects/imap/releases/download/v0.3.5/imap_0.3.5_linux_armv6.tar.gz"
      sha256 "dbc20586292bc10e7fbb30a706269985c723d71ad820512be26b263616fe7d49"

      def install
        bin.install "imap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/creativeprojects/imap/releases/download/v0.3.5/imap_0.3.5_linux_arm64.tar.gz"
      sha256 "ed0cf25c836f0658e887aa7e2c62f24c538a50dcd98b9fe38ff5815fcb399315"

      def install
        bin.install "imap"
      end
    end
  end

  head "https://github.com/creativeprojects/imap.git"
end
