# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imap < Formula
  desc "IMAP tools: backup, copy, move your emails between servers and locally"
  homepage "https://github.com/creativeprojects/imap"
  version "0.3.4"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/creativeprojects/imap/releases/download/v0.3.4/imap_0.3.4_darwin_arm64.tar.gz"
      sha256 "328c60f09e6f74fbaa0a91fa443d15d529255718c1ad910eef2b1bb1019639b6"

      def install
        bin.install "imap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/creativeprojects/imap/releases/download/v0.3.4/imap_0.3.4_darwin_amd64.tar.gz"
      sha256 "ef2d1dc44aecf001cd062fd01e5516a343f84a8003830da720e9079ce5b363d3"

      def install
        bin.install "imap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/creativeprojects/imap/releases/download/v0.3.4/imap_0.3.4_linux_armv6.tar.gz"
      sha256 "4ad29affdcb375a61707e73fc0f4e8eea768707ec0926c76322266ae57281e96"

      def install
        bin.install "imap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/creativeprojects/imap/releases/download/v0.3.4/imap_0.3.4_linux_arm64.tar.gz"
      sha256 "09c92b901a79ef4c81c21721437537011a6556547619126fd46452c1bab7c12e"

      def install
        bin.install "imap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/creativeprojects/imap/releases/download/v0.3.4/imap_0.3.4_linux_amd64.tar.gz"
      sha256 "f395901812c66cf5752311fce6979d0b4ff375441520ead5543a1945e06d9bbe"

      def install
        bin.install "imap"
      end
    end
  end

  head "https://github.com/creativeprojects/imap.git"
end
