# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resticprofile < Formula
  desc "Configuration profiles for restic backup"
  homepage "https://github.com/creativeprojects/resticprofile"
  version "0.27.0"
  license "GPL-3.0-only"

  depends_on "restic" => :optional

  on_macos do
    on_intel do
      url "https://github.com/creativeprojects/resticprofile/releases/download/v0.27.0/resticprofile_no_self_update_0.27.0_darwin_amd64.tar.gz"
      sha256 "88e94ab571c07d669c00cc7cca27823b901c265dcb4d76fa6f683075e538dae2"

      def install
        bin.install "resticprofile"
      end
    end
    on_arm do
      url "https://github.com/creativeprojects/resticprofile/releases/download/v0.27.0/resticprofile_no_self_update_0.27.0_darwin_arm64.tar.gz"
      sha256 "c2ab76401667a5624d2ef0663ddd980df33a55f26bd6d30037a8d262686785cd"

      def install
        bin.install "resticprofile"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/creativeprojects/resticprofile/releases/download/v0.27.0/resticprofile_no_self_update_0.27.0_linux_amd64.tar.gz"
        sha256 "26180d8ac7bac36db77107b2fbfcf45f9690022fdaf43f13ad8e23dbfffd352f"

        def install
          bin.install "resticprofile"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/creativeprojects/resticprofile/releases/download/v0.27.0/resticprofile_no_self_update_0.27.0_linux_armv6.tar.gz"
        sha256 "e45413c2797428ad1a159c9a7e49376e5404f73a14e53a593063b39738c18586"

        def install
          bin.install "resticprofile"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/creativeprojects/resticprofile/releases/download/v0.27.0/resticprofile_no_self_update_0.27.0_linux_arm64.tar.gz"
        sha256 "294ce96dc582ecd28220e0bc8f441b0426a8cc951b3b9c3118b85d3bad72a3d3"

        def install
          bin.install "resticprofile"
        end
      end
    end
  end

  head "https://github.com/creativeprojects/resticprofile.git"

  test do
    (testpath/"restic_repo").mkdir
    (testpath/"password.txt").write("key")
    (testpath/"profiles.yaml").write <<~EOS
      default:
        repository: "local:#{testpath}/restic_repo"
        password-file: "password.txt"
        initialize: true
    EOS

    (testpath/"testfile").write("This is a testfile")

    system "#{bin}/resticprofile", "backup", "testfile"
    system "#{bin}/resticprofile", "restore", "latest", "-t", "#{testpath}/restore"
    assert compare_file "testfile", "#{testpath}/restore/testfile"
  end
end
