# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resticprofile < Formula
  desc "Configuration profiles for restic backup"
  homepage "https://github.com/creativeprojects/resticprofile"
  version "0.33.0"
  license "GPL-3.0-only"

  depends_on "restic" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/creativeprojects/resticprofile/releases/download/v0.33.0/resticprofile_no_self_update_0.33.0_darwin_amd64.tar.gz"
      sha256 "fab2a1454d7285fde636e622a2e28efe5248555f7984ba303a09d3b1e18c9ab3"

      define_method(:install) do
        bin.install "resticprofile"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/creativeprojects/resticprofile/releases/download/v0.33.0/resticprofile_no_self_update_0.33.0_darwin_arm64.tar.gz"
      sha256 "cc6faff2fe01ad2fe323bef7e999971fe8324dcd26ca324ddca7c73deae17b38"

      define_method(:install) do
        bin.install "resticprofile"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/creativeprojects/resticprofile/releases/download/v0.33.0/resticprofile_no_self_update_0.33.0_linux_amd64.tar.gz"
      sha256 "e8198836494611c69b51c53b0e10ff7e9ec12e1ebdce3bcbab25a8dd65c30fb0"
      define_method(:install) do
        bin.install "resticprofile"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/creativeprojects/resticprofile/releases/download/v0.33.0/resticprofile_no_self_update_0.33.0_linux_armv6.tar.gz"
      sha256 "cc6a977e02d5bfddf362f003321789dd966b0f96f734d34075396ff3ceb1f6d4"
      define_method(:install) do
        bin.install "resticprofile"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/creativeprojects/resticprofile/releases/download/v0.33.0/resticprofile_no_self_update_0.33.0_linux_arm64.tar.gz"
      sha256 "a9b54860f1fc0f0920a94be91fa26c318c3bb0ae49dc14e86fb11ab577bf3659"
      define_method(:install) do
        bin.install "resticprofile"
      end
    end
  end

  head "https://github.com/creativeprojects/resticprofile.git"

  test do
    (testpath/"restic_repo").mkdir
    (testpath/"password.txt").write("key")
    (testpath/"profiles.yaml").write <<~EOS
      default:
        repository: "local:#{testpath}/restic_repo"
        password-file: "password.txt"
        initialize: true
    EOS

    (testpath/"testfile").write("This is a testfile")

    system "#{bin}/resticprofile", "backup", "testfile"
    system "#{bin}/resticprofile", "restore", "latest", "-t", "#{testpath}/restore"
    assert compare_file "testfile", "#{testpath}/restore/testfile"
  end
end
